### ISSUE TITLE
[request] Add Wonderswam and Wonderswam color compatibility

### ISSUE THREAD

**Issue by sergioad** [robertybob/es-theme-simplebigart#8]
Hello friend could you add Wonderswam and Wonderswam color compatibility for your theme? sincerely it is my favorite ES theme and I wish have those system pages themed

**Comment by robertybob** [comment]
Hi @sergioad I'm not the original creator, but I'm happy to take pull requests to add new systems. I don't have the time and/or skills to do it myself :) Sorry.

**Comment by sergioad** [comment]
Thanks

**Comment by sergioad** [comment]
Friend Robervik from the RetroPie forums fixed the theme, could you merge it please? https://dl.dropboxusercontent.com/u/60872572/EmulationStation/SimpleBigArt/simplebigart-wonderswan.zip

**Comment by robertybob** [comment]
@Sergioad I'll be able to do it on Tuesday evening :)

**Comment by sergioad** [comment]
Ok

**Comment by robertybob** [comment]
@sergioad Done :)

**Comment by sergioad** [comment]
Thank you
